mcobbett copyright build pipelines
galasa-dev/automation pull request #327
Opened 2023-10-06 09:17 UTC by techcobweb

- Working on the github copyright app pipelines still..
- Another attempt
- Stopping here for now
- Adding comments to explain progress so far
- Remove task that was needed for testing purposes
- revert make task to what it was in main
- Make with params

2023-10-06 09:22 UTC, galasa-team commented
Build successful

2023-10-09 09:38 UTC, galasa-team commented
Build successful

2023-10-09 09:47 UTC, jadecarino requested changes

2023-10-09 09:47 UTC, jadecarino commented on pipelines/pipelines/githubapp-copyright/build-pr.yaml
> +    params:
Can you add this in here:
```
runAfter:
      - git-verify
```

2023-10-09 10:04 UTC, techcobweb commented on pipelines/pipelines/githubapp-copyright/build-pr.yaml
> +    params:
Well spotted. Fixed.

2023-10-09 10:05 UTC, jadecarino approved these changes

2023-10-09 10:09 UTC, galasa-team commented
Build successful

2023-10-09 10:53 UTC, merged