Automate the release of Maven artefacts to the Sonatype staging repo.
galasa-dev/automation pull request #465
Opened 2024-02-14 10:52 UTC by Akyiaa

added sonatype creds (mavencreds) to galasabld

2024-02-14 10:57 UTC, galasa-team commented
Build successful

2024-02-14 15:53 UTC, galasa-team commented
Build successful

2024-02-15 11:31 UTC, galasa-team commented
Build successful

2024-02-15 15:32 UTC, galasa-team commented
Build successful

2024-02-15 16:21 UTC, jadecarino requested changes
Hi Fiona, thanks for making these changes. Just a few changes please to reflect what the script's purpose is more accurately, and a small correction with the parameters in the Galasabld Task.

Also; could you also please add the mavencreds volume to the bottom of the Galasabld Task?

2024-02-15 16:21 UTC, jadecarino commented on pipelines/tasks/galasabld-command.yaml
> +    defualt: harbor.galasa.dev/galasadev/galasabld-amd64:$(params.galasabldImageTag)
I don't think it's possible to reference a parameter from inside a parameter, so can we change this to just the part before the colon?

2024-02-15 16:21 UTC, jadecarino commented on pipelines/tasks/galasabld-command.yaml
> +    image: $(params.image)
This would then become $(params.image):$(params.galasabldImageTag)

2024-02-15 16:21 UTC, jadecarino commented on releasePipeline/05-deploy-maven-galasa.sh
> +# Objectives: Deletes all the release-type branches in each github repo
Can we update this for this scripts purpose please?

2024-02-15 16:21 UTC, jadecarino commented on releasePipeline/05-deploy-maven-galasa.sh
> +
We'll need another function similar to these to ask the user for the release version number x.xx.x and that should set the $version parameter for the script - similar to how the release type is set

2024-02-15 16:21 UTC, jadecarino commented on releasePipeline/05-deploy-maven-galasa.sh
> +    h1 "Deploying all artifacts in github called ${release_type}"
The artefacts are not being deployed from GitHub here - can you change this to 'Deploying all Galasa artefacts at version ${version}' please?

2024-02-15 16:21 UTC, jadecarino commented on releasePipeline/05-deploy-maven-galasa.sh
> +    success "All maven artifacts in github called ${release_type} are now deployed. Yay!"
Same as my previous comment, please reflect what is actually being deployed here

2024-02-15 16:23 UTC, jadecarino commented on releasePipeline/05-deploy-maven-galasa.sh
> +
Sorry ignore this I missed the function :)

2024-02-15 16:25 UTC, jadecarino requested changes
Also please can we change the script files name to the place in which it should be in the release? So I believe it should be 30- (the same as the PipelineRun's file name)

2024-02-15 16:45 UTC, galasa-team commented
Build successful

2024-02-16 10:27 UTC, galasa-team commented
Build failed, see http://localhost:8001/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/namespaces/galasa-build/pipelineruns/repo-automation-pr-465-b6ws4 for details. If you are unable to do so, please contact a member of the Galasa team.

2024-02-16 10:35 UTC, galasa-team commented
Build successful

2024-02-16 13:57 UTC, jadecarino requested changes
Just one small typo to fix - then please go ahead and delete the galasabld-copy file and this can be merged :)

2024-02-16 13:57 UTC, jadecarino commented on pipelines/tasks/galasabld-command.yaml
> +    defualt: harbor.galasa.dev/galasadev/galasabld-amd64
Just realised a spelling typo here :) After this is fixed this looks good

2024-02-16 14:45 UTC, jadecarino approved these changes

2024-02-16 14:58 UTC, merged