Post-release 0.32.0 updates
galasa-dev/automation pull request #498
Opened 2024-03-14 09:53 UTC by KirbyKatcher

updated release instructions to have instructions with galasactl commands and removed some markdown issues
Shell script to run all of pre-release

2024-03-14 09:59 UTC, galasa-team commented
Build successful

2024-03-14 16:37 UTC, galasa-team commented
Build successful

2024-03-20 14:57 UTC, jadecarino requested changes
A couple of small changes but overall looks good, thanks for automating this process, will save us time!

2024-03-20 14:57 UTC, jadecarino commented on releasePipeline/prerelease.md
> +4. Send the [mvp image](https://development.galasa.dev/prerelease/maven-repo/mvp/dev/galasa/galasa-isolated-mvp) to Will Yates to perform the MEND scan to check for any vulnerabilities before moving
Minor point but let's add my name in here as well as Will, as if he is not available to do this, I can.

2024-03-20 14:57 UTC, jadecarino commented on releasePipeline/prerelease.md
> +9. Send the [mvp image](https://development.galasa.dev/prerelease/maven-repo/mvp/dev/galasa/galasa-isolated-mvp) to Will Yates to perform the MEND scan to check for any vulnerabilities before moving
Same here

2024-03-20 14:57 UTC, jadecarino commented on releasePipeline/release.md
> +galasactl properties set --namespace galasaecosystem --name runtime.version  --value 0.33.0 --bootstrap https://galasa-galasa-prod.cicsk8s.hursley.ibm.com/bootstrap
We should make it clear that value `0.33.0` in these examples should be replaced with the new Galasa development version. Alternatively could we script this with `--devVersion` being passed in?

2024-03-20 14:57 UTC, jadecarino commented on releasePipeline/05-helm-charts.sh
> +}
Does this commented out bit need to be finished?

2024-03-27 14:06 UTC, galasa-team commented
Build successful

2024-04-02 16:23 UTC, galasa-team commented
Build successful

2024-04-02 16:27 UTC, galasa-team commented
Build successful

2024-04-02 16:41 UTC, galasa-team commented
Build successful

2024-04-03 15:01 UTC, eamansour approved these changes

2024-04-03 15:05 UTC, merged