Added gh workflow trigger task and a job in run-test pipeline
galasa-dev/automation pull request #599
Opened 2024-08-22 15:55 UTC by jaydee029

For issue
- galasa-dev/projectmanagement#1934

2024-08-22 15:56 UTC, galasa-team commented
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

2024-08-23 10:01 UTC, jadecarino requested changes
Hi Dhruv - A few minor changes to make please, but really good work for your first time creating something for Tekton. I'm hoping it gave you a good insight into the differences between it and GH Actions. A couple changes for clarity and then 2 minor fixes.

2024-08-26 05:13 UTC, jaydee029 commented on pipelines/tasks/gh-workflow-trigger.yaml
> +
done

2024-08-26 05:13 UTC, jaydee029 commented on pipelines/tasks/gh-workflow-trigger.yaml
> +     echo $GH_TOKEN | gh auth login --with-token  # not necessary just incase authentication fails
donr

2024-08-26 05:13 UTC, jaydee029 commented on pipelines/tasks/gh-workflow-trigger.yaml
> +          name: GALASA_TEAM_GITHUB_TOKEN
done

2024-08-26 05:14 UTC, galasa-team commented
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

2024-08-26 05:14 UTC, jaydee029 commented on pipelines/tasks/gh-workflow-trigger.yaml
> +     gh workflow run $(params.workflowName) --repo https://github.com/galasa-dev/$(params.repoName) --ref $(params.refBranch)
done

2024-08-27 15:25 UTC, galasa-team commented
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

2024-08-27 15:26 UTC, galasa-team commented
Build successful

2024-09-10 12:47 UTC, merged